#!/usr/bin/env bash

set -eu

release_keys () {
    echo -ne "\0\0\0\0\0\0\0\0"	# no keys
}

portid="${1}"

# type a single digit.
digit2hidevt () {
  local digit="${1}"
  local keycode
  case "${digit}" in
    0) keycode='\x27' ;;
    1) keycode='\x1e' ;;
    2) keycode='\x1f' ;;
    3) keycode='\x20' ;;
    4) keycode='\x21' ;;
    5) keycode='\x22' ;;
    6) keycode='\x23' ;;
    7) keycode='\x24' ;;
    8) keycode='\x25' ;;
    9) keycode='\x26' ;;
    *) err "tried to use ${digit} as digit, could not look up" ;;
  esac
  echo -ne "\0\0${keycode}\0\0\0\0\0"
  release_keys
}

# type a string (of digits)
str2hidevts () {
  local ct=0
  local string="${1}"
  while [[ "${ct}" -lt "${#string}" ]] ; do
    digit2hidevt "${string:$ct:1}"
    ct=$((ct + 1))
  done
}

SCROLL_LOCK="\0\0\x53\0\0\0\0\0"

exec > /dev/tinypilot-hid-gadget/hid.keyboard

release_keys
echo -ne "${SCROLL_LOCK}"
release_keys
echo -ne "${SCROLL_LOCK}"
release_keys
str2hidevts "${portid}"
echo -ne "\0\0\x28\0\0\0\0\0" # enter
release_keys
